### PR TITLE
Add configurable support of outputing a reportfile per suite

### LINKED ISSUE #4: One report file generated when running multiple suites
Hi, 
I am using this package (which is great) and running multiple test suites in different directories.
When running the command:
behat --config behat.yml -f pretty -o std -f junit -o reports -f cucumber_json -o reports

After the command has finished I only get one report file by the name of the last suite.

I have this in my behat.yml file:
      Vanare\BehatCucumberJsonFormatter\Extension:
        fileNamePrefix: report-
        outputDir: %paths.base%/reports

Can you please help me see why I only get one file?
Thanks!

### PR DESCRIPTION
**Pull request by grEvenX**
Opening a PR to start a discussion around how to solve the output naming and results of the current behat-cucumber-formatter extension. This PR should close issue #4.

This PR is backwards-compatible and doesn't change anything to the current behaviour of the extension, a report file named by the name of the suite can be generated by specifying the option `resultFilePerSuite: true` in the extension configuration.
I do however find the current implementation a bit "odd", and I wonder if there is room to make further improvements here?
The main issues I see are summarised below.

1. The default filename is weird, it's based on the last feature tested in the default suite, but it contains all features in the default suite. Is there a specific reason to why it behaves this way currently?

Example:
I have a default suite with two feature files "calculator.feature" and "eat-cukes.feature".
I run the test suite with the command `behat -s default -f cucumber_json`.
The generated report contains the results from `calculator.feature` and `eat-cukes.feature`, but the report is named `report-tmp-behat-a9cf46741df008fe789ae0a7de708413-features-default-eat-cukes.json` which seems like an overly complex and strange default to me?

2. The current behaviour is that if you have multiple suites defined and don't specify the suite when you run the tests, then the cucumber json formatter only writes the result of the last run suite to the report file. As a user I would expect that the report file would contain all the tests that Behat ran.

Would be good to get some feedback on these topics and the implementation to see how it can progress next :)

### CODE REVIEW

**Comment by cawolf** [comment]
to 1.: no, there is no specific reason for the result file name. You are free to define a new, more consistent behaviour.

to 2.: sure, that would be a consistent behaviour. Currently, we explicitely use the plugin for separated suites only, but solving that issue would broaden the use case of the plugin.

**Comment by grEvenX** [comment]
@cawolf Updated the PR now based on the things discussed. Also added some documentation about the configuration parameters. Can you review and see if there's any changes needed?

**Comment by cawolf** [comment]
I will have a deeper look tomorrow, but at a glance this looks fine.

**Review by cawolf — CHANGES_REQUESTED** [review]
Ok, LGTM. Seems you have to tweak the 5.6 travis job to not use a memory limit, as it is failing due to `Allowed memory size of 1610612736 bytes exhausted`.

**Comment by cawolf** [comment]
To be honest: we are in 2020, we may also drop PHP 5.6 from the supported versions. For the sake of this PR, you can stop trying to make that work, ok? We can drop 5.6 in a separate branch.

**Review by cawolf — APPROVED** [review]

**Comment by grEvenX** [comment]
@cawolf Thanks, I was going a bit insane, tried to fire up 5.4 in a docker environment to get it tested here. Currently used to follow the latest PHP versions, so going back to a world where we actually need to be compatibly with older versions was a new challenge for me 😂 
I cleaned up the commits a bit, does it seem fine now or do you want it to be squashed to a single commit?

**Comment by cawolf** [comment]
LGTM. Don't worry, I will squash it on merging. Thank you for your contribution!

**Pull request merged**
